### ISSUE TITLE
Unable to post notifications - Notification type error

### ISSUE THREAD

**Issue by anshuman92** [cap-js/notifications#44]
Hi,

I am trying to post notifications with custom notification types as well as default notification types. In both cases, I get errors where notification types are not registered.

Error with custom notification types - `"msg":"Emit failed {event: 'NewQuestionnariePublished',cause: Error: NotificationType for key <appname>/NewQuestionnariePublished Version 1 does not exist at NotifyToRest.postNotification (/home/vcap/deps/0/node_modules/@cap-js/notifications/srv/notifyToRest.js:34:21)`

Error with standard notification types - `"msg":"Emit failed {event: 'Default', cause: Error: NotificationType for key Default Version 1 does not exist at NotifyToRest.postNotification (/home/vcap/deps/0/node_modules/@cap-js/notifications/srv/notifyToRest.js:34:21)`

Do we need to register separately for the notification types before using them?

Kindly clarify.

Regards,
Anshuman

**Comment by anshuman92** [comment]
Hi, I was able to solve this issue with a work around. However, I would suggest you to implement the same in your code.

library method - content-deployment.js - > deployNotificationTypes() does not get called without explicit call. Right now, in our srv folder -> server.js we specifically required the above js file. This checks for the notification types declared in a folder path as specified in package.json and therefore then it got invoked while the server was started, which then created the notification types.

The readme file also did not mention anything explicitly about the notification types. May be, you should upgrade that as well.

Regards,
Anshuman
