### ISSUE TITLE
Notification Content Deployer Failing

### ISSUE THREAD

**Issue by gopalanand333** [cap-js/notifications#45]
Hi Team, 
The notification content deployer is failing when trying to deploy the application. It works it the service is bound to an instance of SAP Alert Notification Service.
The error is:
```
2024-02-12T14:25:52.745+0000 [APP/TASK/notification-content-deployment/0] STDOUT {"date":"Mon Feb 12 2024 14:25:52 GMT+0000 (Coordinated Universal Time)","error":{"cause":{},"name":"ErrorWithCause"},"exception":true,"level":"error","logger":"sap-cloud-sdk-logger","message":"uncaughtException: Failed to build headers.\nErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","msg":"ErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","os":{"loadavg":[11.07,12.18,12.43],"uptime":1018733.62},"process":{"argv":["/home/vcap/deps/0/node/bin/node","/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js"],"cwd":"/home/vcap/app","execPath":"/home/vcap/deps/0/node/bin/node","gid":2000,"memoryUsage":{"arrayBuffers":121629,"external":2864465,"heapTotal":20570112,"heapUsed":17030352,"rss":68096000},"pid":7,"uid":2000,"version":"v18.19.0"},"stack":"ErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","test":"exception","timestamp":"2024-02-12T14:25:52.743Z","trace":[{"column":15,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHeaders","line":295,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":21,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"async buildHttpRequest","line":53,"method":null,"native":false},{"column":42,"file":"async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":null,"line":71,"method":null,"native":false},{"column":20,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async getNotificationTypes","line":64,"method":null,"native":false},{"column":25,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async processNotificationTypes","line":251,"method":null,"native":false},{"column":5,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js","function":"async deployNotificationTypes","line":14,"method":null,"native":false},{"column":15,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"headerFromTokens","line":39,"method":null,"native":false},{"column":28,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"getAuthenticationRelatedHeaders","line":107,"method":null,"native":false},{"column":19,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"buildAuthorizationHeaders","line":134,"method":null,"native":false},{"column":84,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js","function":"buildHeadersForDestination","line":12,"method":null,"native":false},{"column":68,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHeaders","line":292,"method":null,"native":false},{"column":27,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHttpRequest","line":53,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":42,"file":"async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":null,"line":71,"method":null,"native":false},{"column":20,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async getNotificationTypes","line":64,"method":null,"native":false},{"column":25,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async processNotificationTypes","line":251,"method":null,"native":false}],"written_at":"2024-02-12T14:25:52.743Z","written_ts":1707747952743}
2024-02-12T14:25:52.745+0000 [APP/TASK/notification-content-deployment/0] STDOUT {"date":"Mon Feb 12 2024 14:25:52 GMT+0000 (Coordinated Universal Time)","error":{"cause":{},"name":"ErrorWithCause"},"exception":true,"level":"error","logger":"sap-cloud-sdk-logger","message":"uncaughtException: Failed to build headers.\nErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","msg":"ErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","os":{"loadavg":[11.07,12.18,12.43],"uptime":1018733.62},"process":{"argv":["/home/vcap/deps/0/node/bin/node","/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js"],"cwd":"/home/vcap/app","execPath":"/home/vcap/deps/0/node/bin/node","gid":2000,"memoryUsage":{"arrayBuffers":121653,"external":2864529,"heapTotal":20570112,"heapUsed":17176704,"rss":68096000},"pid":7,"uid":2000,"version":"v18.19.0"},"stack":"ErrorWithCause: Failed to build headers.\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:295:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:21)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)\n    at async deployNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js:14:5)\nCaused by:\nError: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials\n    at headerFromTokens (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:39:15)\n    at getAuthenticationRelatedHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:107:28)\n    at buildAuthorizationHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js:134:19)\n    at buildHeadersForDestination (/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js:12:84)\n    at buildHeaders (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:292:68)\n    at buildHttpRequest (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:53:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:71:42\n    at async getNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:64:20)\n    at async processNotificationTypes (/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js:251:25)","test":"exception","timestamp":"2024-02-12T14:25:52.745Z","trace":[{"column":15,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHeaders","line":295,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":21,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"async buildHttpRequest","line":53,"method":null,"native":false},{"column":42,"file":"async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":null,"line":71,"method":null,"native":false},{"column":20,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async getNotificationTypes","line":64,"method":null,"native":false},{"column":25,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async processNotificationTypes","line":251,"method":null,"native":false},{"column":5,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/content-deployment.js","function":"async deployNotificationTypes","line":14,"method":null,"native":false},{"column":15,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"headerFromTokens","line":39,"method":null,"native":false},{"column":28,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"getAuthenticationRelatedHeaders","line":107,"method":null,"native":false},{"column":19,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/authorization-header.js","function":"buildAuthorizationHeaders","line":134,"method":null,"native":false},{"column":84,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/header-builder-for-destination.js","function":"buildHeadersForDestination","line":12,"method":null,"native":false},{"column":68,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHeaders","line":292,"method":null,"native":false},{"column":27,"file":"/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":"buildHttpRequest","line":53,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"process.processTicksAndRejections","line":95,"method":"processTicksAndRejections","native":false},{"column":42,"file":"async /home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js","function":null,"line":71,"method":null,"native":false},{"column":20,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async getNotificationTypes","line":64,"method":null,"native":false},{"column":25,"file":"/home/vcap/app/node_modules/@cap-js/notifications/lib/notificationTypes.js","function":"async processNotificationTypes","line":251,"method":null,"native":false}],"written_at":"2024-02-12T14:25:52.745Z","written_ts":1707747952745}
2024-02-12T14:25:55.764+0000 [APP/TASK/notification-content-deployment/0] STDOUT Exit status 1
2024-02-12T14:25:55.939+0000 [CELL/0] STDOUT Cell 33f1a3f2-ba19-4b38-8ea3-d7769595d920 stopping instance f07d702a-a0a5-47ef-bbd9-4ff696214a6e
2024-02-12T14:25:55.939+0000 [CELL/0] STDOUT Cell 33f1a3f2-ba19-4b38-8ea3-d7769595d920 destroying container for instance f07d702a-a0a5-47ef-bbd9-4ff696214a6e
2024-02-12T14:25:59.687+0000 [CELL/0] STDOUT Cell 33f1a3f2-ba19-4b38-8ea3-d7769595d920 successfully destroyed container for instance f07d702a-a0a5-47ef-bbd9-4ff696214a6e
```

Does it mean that we need to bind the alert notification service to the application content deployer? if yes:
- It should be clearly documented
- The cds add mta should add the required service instance configuration and binding to the content deployer.

**Comment by gopalanand333** [comment]
**This issue is fixed, It was occurring due to wrong client credentials that I had created at the destination created at the subaccount.**
